### ISSUE TITLE
Fix entity freezing

### ISSUE THREAD

**Issue by Skyshayde** [Skyshayde/Vampirism#1]
victim entities aren't frozen despite receiving slowness 127,  I need to investigate the cause of this or figure out a different method to freeze them.  I've confirmed that slowness does affect mobs.  

I'd also like to make sucking blood not apply knock back.

**Comment by maxanier** [comment]
I think the reason slowness 127 is not working is that MC multiplies the basic Potion MOVEMENT_SPEED attribute modifier (-0.15) by the amplifier value (127) which results in a very negative final modifier.

The computation of the final movement speed is calculated as follows (for a type 2 operation)
`Result = Base value * (1 + modifier)`
Since the modifier is smaller -1, the resulting speed is negative. I did not check what exactly happens then, but I think we want to avoid that. So the value for a type 2 modifier should always be >-1

**Comment by Skyshayde** [comment]
i'm real dumb, I was using a duration of 1 for the effect because I forgot it was in ticks
